### ISSUE TITLE
Poco Generator v2.37.1 - // Failed to read database schema in LoadTables().

### ISSUE THREAD

**Issue by lpmplpmp** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#455]
I like to use poco generator in my sample project, and only get what I want and copy to my code first real project.
A few weeks ago, I tried to use  v2.32.0.  All the EF code work as expected.

Today, I tried to create only one table in the database, and use v2.37.1 to generate code.

What I got in cs file is as the following.
Hope someone can test it too.
Please let me know if you need more information, I may make a youtube video to re-generate this issue.

// -----------------------------------------------------------------------------------------
// Failed to read database schema in LoadTables().
// -----------------------------------------------------------------------------------------
The multi-part identifier "C.TABLE_NAME" could not be bound.
The multi-part identifier "C.TABLE_NAME" could not be bound.
The multi-part identifier "C.TABLE_NAME" could not be bound.
The multi-part identifier "C.TABLE_NAME" could not be bound.
System.Data.SqlClient.SqlException
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.VisualStudio.TextTemplatingA02D5A3083DD66A51A4BDC5FEBF7F33FD4D3E4E6FD0BC26BD210679254D4D71E29717544BDFADCE6F8CB962AC09890C0DC6571A176F36B740B21C2A37EAA1BE6.GeneratedTextTransformation.SqlServerSchemaReader.ReadSchema() in d:\0_mydocument\documents\visual studio 2017\Projects\ItHandyGuy.OnlineGame\ItHandyGuy.OnlineGame.Ui.ConsoleApp\EF.Reverse.POCO.Core.ttinclude:line 2733
   at Microsoft.VisualStudio.TextTemplatingA02D5A3083DD66A51A4BDC5FEBF7F33FD4D3E4E6FD0BC26BD210679254D4D71E29717544BDFADCE6F8CB962AC09890C0DC6571A176F36B740B21C2A37EAA1BE6.GeneratedTextTransformation.LoadTables(DbProviderFactory factory) in d:\0_mydocument\documents\visual studio 2017\Projects\ItHandyGuy.OnlineGame\ItHandyGuy.OnlineGame.Ui.ConsoleApp\EF.Reverse.POCO.Core.ttinclude:line 722

**Comment by sjh37** [comment]
Hi. This has already been fixed, but not yet released.
See https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/commit/2b7fbb27c8a044fcf77467eccc2e9260e12e587a

Make the same change to your code and check if its ok.

**Comment by lpmplpmp** [comment]
I will try again when you release the new version.
Thank you very much.

**Comment by lpmplpmp** [comment]
Hi. This has already been fixed, but not yet released.
See [2b7fbb2](https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/commit/2b7fbb27c8a044fcf77467eccc2e9260e12e587a)
Make the same change to your code and check if its ok.
-->
- C.TABLE_NAME NOT IN ('EdmMetadata', '__MigrationHistory', '__RefactorLog', 'sysdiagrams')
+ c.TABLE_NAME NOT IN ('EdmMetadata', '__MigrationHistory', '__RefactorLog', 'sysdiagrams')
I have done the same changes, but it doesn't work for me.

I will try again when you release the new version.
Thank you very much.

**Comment by sjh37** [comment]
This was the mixed upper/lower-case table alias problem, which fails on case-sensitive collations. It was fixed shortly after 2.37.1, and in v4 schema reading has moved into the `efrpg` tool, so that query no longer exists. Closing.
