### ISSUE TITLE
Unable to find the requested .Net Framework Data Provider

### ISSUE THREAD

**Issue by statler** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#534]
I have a template that works perfectly with my SQL database, but when I try and get it to generate for my Compact db, I get an error when it tries to get the factory;

```
// -----------------------------------------------------------------------------------------
// Failed to load provider "System.Data.SqlServerCe.4.0".
// -----------------------------------------------------------------------------------------
Unable to find the requested .Net Framework Data Provider.  It may not be installed.
System.ArgumentException
   at System.Data.Common.DbProviderFactories.GetFactory(String providerInvariantName)
   at Microsoft.VisualStudio.TextTemplating1621FD8D5C1341A247CB3E8D31B8B3474F6650C534C6651955E08E98D2F2F39A97AA74CE70735376C5AAD015903974F1578F04EA8809797E9A45584700C0484C.GeneratedTextTransformation.GetDbProviderFactory() in C:\Users\dennisg\source\repos\CivilProv9\EfDataLayer\Contexts\Approvals\EF.Reverse.POCO.Core.ttinclude:line 678
```

When I run the following in my compiled code, the factory is correctly identified, so I can't for the life of me figure out why this exception happens.

    DbProviderFactory factory = DbProviderFactories.GetFactory("System.Data.SqlServerCe.4.0");

My config is as follows. Same exception whether I get the connectionstringname from the config, or if I set the providername and connectionstring explicitly.

    Settings.ConnectionStringName = "cpCeContext";

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
    <!-- For more information on Entity Framework configuration, visit http://go.microsoft.com/fwlink/?LinkID=237468 -->
    <section name="entityFramework" type="System.Data.Entity.Internal.ConfigFile.EntityFrameworkSection, EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />
    <!-- For more information on Entity Framework configuration, visit http://go.microsoft.com/fwlink/?LinkID=237468 -->
  </configSections>
  <entityFramework>
    <providers>
      <provider invariantName="System.Data.SqlClient" type="System.Data.Entity.SqlServer.SqlProviderServices, EntityFramework.SqlServer" />
      <provider invariantName="System.Data.SqlServerCe.4.0" type="System.Data.Entity.SqlServerCompact.SqlCeProviderServices, EntityFramework.SqlServerCompact" />
    </providers>
    <defaultConnectionFactory type="System.Data.Entity.Infrastructure.SqlCeConnectionFactory, EntityFramework">
      <parameters>
        <parameter value="System.Data.SqlServerCe.4.0" />
      </parameters>
    </defaultConnectionFactory>
  </entityFramework>
  <system.data>
    <DbProviderFactories>
      <remove invariant="System.Data.SqlServerCe.4.0" />
      <add name="Microsoft SQL Server Compact Data Provider 4.0" invariant="System.Data.SqlServerCe.4.0" description=".NET Framework Data Provider for Microsoft SQL Server Compact" type="System.Data.SqlServerCe.SqlCeProviderFactory, System.Data.SqlServerCe, Version=4.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91" />
    </DbProviderFactories>
  </system.data>
  <connectionStrings>
    <add name="cpContext" connectionString="data source=XXXX\SQLEXPRESS;initial catalog=QADemoDB_66;integrated security=True;MultipleActiveResultSets=True;App=EntityFramework" providerName="System.Data.SqlClient" />
    <add name="cpCeContext" providerName="System.Data.SqlServerCe.4.0" connectionString="Data Source=C:\QADemoDB_66.cdb" />
  </connectionStrings>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="AutoMapper" publicKeyToken="be96cd2c38ef1005" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-9.0.0.0" newVersion="9.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

**Comment by statler** [comment]
Here is a basic project I created that fails like this on my system.

[ClassLibrary4.zip](https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/files/3652246/ClassLibrary4.zip)

**Comment by statler** [comment]
Sorry - accidentally closed

**Comment by sjh37** [comment]
Here is my app.config that works ok with SqlCE
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <configSections>
        <section name="entityFramework" type="System.Data.Entity.Internal.ConfigFile.EntityFrameworkSection, EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />
        <!-- For more information on Entity Framework configuration, visit http://go.microsoft.com/fwlink/?LinkID=237468 -->
    </configSections>
    <entityFramework>
        <defaultConnectionFactory type="System.Data.Entity.Infrastructure.LocalDbConnectionFactory, EntityFramework">
            <parameters>
                <parameter value="v11.0" />
            </parameters>
        </defaultConnectionFactory>
        <providers>
            <provider invariantName="System.Data.SqlClient" type="System.Data.Entity.SqlServer.SqlProviderServices, EntityFramework.SqlServer" />
        </providers>
    </entityFramework>
    <connectionStrings>
        <add name="MyDbContext" providerName="System.Data.SqlClient" connectionString="Data Source=(local);Initial Catalog=northwind;Integrated Security=True;Application Name=EntityFramework Reverse POCO Generator" />
        <add name="MyDbContextSqlCE4" providerName="System.Data.SqlServerCe.4.0" connectionString="Data Source=|DataDirectory|NorthwindSqlCe40.sdf" />
        <add name="TestDatabase" providerName="System.Data.SqlClient" connectionString="Data Source=(local);Initial Catalog=EfrpgTest;Integrated Security=True;Application Name=EntityFramework Reverse POCO Generator" />
    </connectionStrings>
    <startup>
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5" />
    </startup>
</configuration>
```

In my `database.tt` file I have
```c#
Settings.ConnectionStringName = "MyDbContextSqlCE4";
// Settings.ConnectionString = @"Data Source=C:\MyApplication\App_Data\NorthwindSqlCe40.sdf";
// Settings.ProviderName = "System.Data.SqlServerCe.4.0";
```

Have a look at [this post](https://stackoverflow.com/a/21157563/5884) to see if it helps. 

Also try removing this from your config
```xml
<system.data>
    <DbProviderFactories>
      <remove invariant="System.Data.SqlServerCe.4.0" />
      <add name="Microsoft SQL Server Compact Data Provider 4.0" invariant="System.Data.SqlServerCe.4.0" description=".NET Framework Data Provider for Microsoft SQL Server Compact" type="System.Data.SqlServerCe.SqlCeProviderFactory, System.Data.SqlServerCe, Version=4.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91" />
    </DbProviderFactories>
  </system.data>
```

**Comment by statler** [comment]
This is one of those frustrating cases of completely erroneous error messages. Turns out that you cannot use an SQLCe file with a different extension to sdf. My application uses a .cdb extension for what is otherwise a normal sdf, and apparently this is enough to cause this completely mislabelled exception.

Thanks anyway.

**Comment by sjh37** [comment]
Good to know! Thanks.
