### ISSUE TITLE
Running transformation: System.InvalidCastException: Unable to cast transparent proxy to type 'System.IServiceProvider'.  

### ISSUE THREAD

**Issue by HamedFathi** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#54]
Hi 

I asked my question in stackoverflow more than 2 months ago but no one can not help me. [Link](http://stackoverflow.com/questions/36448114/how-can-i-run-entityframework-reverse-poco-code-first-generator-t4-programmati)

I want to run your T4 without Visual Studio so I downloaded simple-t4-engine for this purpose Simple T4 Engine [Site](https://github.com/jakefoster/simple-t4-engine)

**\* using Simple T4 Engine library is not important I can use any CustomTemplateHost if works ! ***

I wrote some code like this :

```
Engine engine = new Engine();
        TemplatingHost host = new TemplatingHost(System.Text.Encoding.UTF32);
        host.IncludeFileSearchPaths.Add(@"D:\IncludeFiles");

        string templateFileName = "some template";
        // NOTE: Doesn't actually seem to care about the name of the template file?  True, but does use the path to search for stuff.
        host.TemplateFile = templateFileName;
        string input = File.ReadAllText(@"D:\IncludeFiles\T4Files\Database.tt");
        string output = engine.ProcessTemplate(input, host);
        File.WriteAllText(@"D:\IncludeFiles\T4Files\Output.txt", output);

        StringBuilder sb = new StringBuilder();
        foreach (CompilerError error in host.Errors)
        {
           sb.AppendLine(error.ToString());
        }

        File.WriteAllText(@"D:\IncludeFiles\T4Files\ErrorLog.txt", sb.ToString());

```

But I got some errors (Output.txt is Empty)

ErrorLog.txt :

```
error : Running transformation: System.InvalidCastException: Unable to cast transparent proxy to type 'System.IServiceProvider'.
   at Microsoft.VisualStudio.TextTemplating31A64EBEAB614B57E81A1789EC7637709A091834D5CA991E8A2195B15E2A0DFF588B0C98DCEDA8AD6902329A28B09556BDE2A9BEDFA48812CCC12CA1E68AA1C9.GeneratedTextTransformation.GetDTE()
   at Microsoft.VisualStudio.TextTemplating31A64EBEAB614B57E81A1789EC7637709A091834D5CA991E8A2195B15E2A0DFF588B0C98DCEDA8AD6902329A28B09556BDE2A9BEDFA48812CCC12CA1E68AA1C9.GeneratedTextTransformation.GetCurrentProject()
   at Microsoft.VisualStudio.TextTemplating31A64EBEAB614B57E81A1789EC7637709A091834D5CA991E8A2195B15E2A0DFF588B0C98DCEDA8AD6902329A28B09556BDE2A9BEDFA48812CCC12CA1E68AA1C9.GeneratedTextTransformation.GetConfigPaths()
   at Microsoft.VisualStudio.TextTemplating31A64EBEAB614B57E81A1789EC7637709A091834D5CA991E8A2195B15E2A0DFF588B0C98DCEDA8AD6902329A28B09556BDE2A9BEDFA48812CCC12CA1E68AA1C9.GeneratedTextTransformation.GetConnectionString(String& connectionStringName, String& providerName, String& configFilePath)
   at Microsoft.VisualStudio.TextTemplating31A64EBEAB614B57E81A1789EC7637709A091834D5CA991E8A2195B15E2A0DFF588B0C98DCEDA8AD6902329A28B09556BDE2A9BEDFA48812CCC12CA1E68AA1C9.GeneratedTextTransformation.InitConnectionString()
   at Microsoft.VisualStudio.TextTemplating31A64EBEAB614B57E81A1789EC7637709A091834D5CA991E8A2195B15E2A0DFF588B0C98DCEDA8AD6902329A28B09556BDE2A9BEDFA48812CCC12CA1E68AA1C9.GeneratedTextTransformation.GetDbProviderFactory()
   at Microsoft.VisualStudio.TextTemplating31A64EBEAB614B57E81A1789EC7637709A091834D5CA991E8A2195B15E2A0DFF588B0C98DCEDA8AD6902329A28B09556BDE2A9BEDFA48812CCC12CA1E68AA1C9.GeneratedTextTransformation.TransformText()

```

**D:\IncludeFiles contain these files :**
EF.Reverse.POCO.Core.ttinclude
EF.Reverse.POCO.ttinclude
EF6.Utility.CS.ttinclude
# 

**Another try with CMD**

I use CMD and TextTransform.exe with this Command :

TextTransform.exe -I "C:\IncludeFiles" Database1.tt

but shows error :

```
Database1.tt(0,0) : error : Running transformation: System.InvalidCastException: Unable to cast object of type 'Microsoft.VisualStudio.TextTemplating.CommandLine.CommandLineHost' to type 'System.IServiceProvider'.
   at Microsoft.VisualStudio.TextTemplatingbd94e8ea88344f96903a612633001eb5.GeneratedTextTransformation.GetDTE()
   at Microsoft.VisualStudio.TextTemplatingbd94e8ea88344f96903a612633001eb5.GeneratedTextTransformation.GetCurrentProject()
   at Microsoft.VisualStudio.TextTemplatingbd94e8ea88344f96903a612633001eb5.GeneratedTextTransformation.GetConfigPaths()
   at Microsoft.VisualStudio.TextTemplatingbd94e8ea88344f96903a612633001eb5.GeneratedTextTransformation.GetConnectionString(String& connectionStringName, String& providerName, String& configFilePath)
   at Microsoft.VisualStudio.TextTemplatingbd94e8ea88344f96903a612633001eb5.GeneratedTextTransformation.InitConnectionString()
   at Microsoft.VisualStudio.TextTemplatingbd94e8ea88344f96903a612633001eb5.GeneratedTextTransformation.GetDbProviderFactory()
   at Microsoft.VisualStudio.TextTemplatingbd94e8ea88344f96903a612633001eb5.GeneratedTextTransformation.TransformText()

```

I use these two way for other T4 Templates and works and show the result 
Can you guide me Why your T4 can not execute in outside of VS with these ways and help me for fixing problem ?

The answer is so important for me. please help me.
Thanks.

**Comment by sjh37** [comment]
You cannot run this outside of Visual Studio because the generator needs to be able to access EnvDTE so it can add/remove files to/from the project.

**Comment by sjh37** [comment]
I’ll add an answer now.

Regards,

Simon Hughes
